-- CreateTable
CREATE TABLE `Department` (
    `depCode` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `Department_depCode_key`(`depCode`),
    PRIMARY KEY (`depCode`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Subject` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `subCode` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `departmentId` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `pos` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `CourseCode` VARCHAR(191) NOT NULL,
    `subjectId` INTEGER NOT NULL,
    `c01p1` INTEGER NOT NULL,
    `c01p2` INTEGER NOT NULL,
    `c01p3` INTEGER NOT NULL,
    `c01p4` INTEGER NOT NULL,
    `c01p5` INTEGER NOT NULL,
    `c02p1` INTEGER NOT NULL,
    `c02p2` INTEGER NOT NULL,
    `c02p3` INTEGER NOT NULL,
    `c02p4` INTEGER NOT NULL,
    `c02p5` INTEGER NOT NULL,
    `c03p1` INTEGER NOT NULL,
    `c03p2` INTEGER NOT NULL,
    `c03p3` INTEGER NOT NULL,
    `c03p4` INTEGER NOT NULL,
    `c03p5` INTEGER NOT NULL,
    `c04p1` INTEGER NOT NULL,
    `c04p2` INTEGER NOT NULL,
    `c04p3` INTEGER NOT NULL,
    `c04p4` INTEGER NOT NULL,
    `c04p5` INTEGER NOT NULL,
    `c05p1` INTEGER NOT NULL,
    `c05p2` INTEGER NOT NULL,
    `c05p3` INTEGER NOT NULL,
    `c05p4` INTEGER NOT NULL,
    `c05p5` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Student` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `firstName` VARCHAR(191) NOT NULL,
    `lastName` VARCHAR(191) NOT NULL,
    `subjectId` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CIA1` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `studentId` INTEGER NOT NULL,
    `Q1` INTEGER NOT NULL,
    `Q2` INTEGER NOT NULL,
    `Q3` INTEGER NOT NULL,
    `Q4` INTEGER NOT NULL,
    `Q5` INTEGER NOT NULL,
    `Q6` INTEGER NOT NULL,
    `Q7` INTEGER NOT NULL,
    `Q8` INTEGER NOT NULL,
    `Q9` INTEGER NOT NULL,
    `Q10` INTEGER NOT NULL,
    `Q11` INTEGER NOT NULL,
    `Q12` INTEGER NOT NULL,
    `Q13` INTEGER NOT NULL,
    `Q14` INTEGER NOT NULL,
    `Q15` INTEGER NOT NULL,
    `Q16` INTEGER NOT NULL,
    `Q17` INTEGER NOT NULL,
    `Q18` INTEGER NOT NULL,
    `Q19` INTEGER NOT NULL,
    `Q20` INTEGER NOT NULL,
    `Q21` INTEGER NOT NULL,
    `Q22` INTEGER NOT NULL,
    `Q23` INTEGER NOT NULL,
    `Q24` INTEGER NOT NULL,
    `Q25` INTEGER NOT NULL,
    `Q26` INTEGER NOT NULL,
    `Q27` INTEGER NOT NULL,
    `Q28` INTEGER NOT NULL,
    `CO1` INTEGER NOT NULL,
    `CO2` INTEGER NOT NULL,
    `CO3` INTEGER NOT NULL,
    `CO4` INTEGER NOT NULL,
    `CO5` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CIA2` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `studentId` INTEGER NOT NULL,
    `Q1` INTEGER NOT NULL,
    `Q2` INTEGER NOT NULL,
    `Q3` INTEGER NOT NULL,
    `Q4` INTEGER NOT NULL,
    `Q5` INTEGER NOT NULL,
    `Q6` INTEGER NOT NULL,
    `Q7` INTEGER NOT NULL,
    `Q8` INTEGER NOT NULL,
    `Q9` INTEGER NOT NULL,
    `Q10` INTEGER NOT NULL,
    `Q11` INTEGER NOT NULL,
    `Q12` INTEGER NOT NULL,
    `Q13` INTEGER NOT NULL,
    `Q14` INTEGER NOT NULL,
    `Q15` INTEGER NOT NULL,
    `Q16` INTEGER NOT NULL,
    `Q17` INTEGER NOT NULL,
    `Q18` INTEGER NOT NULL,
    `Q19` INTEGER NOT NULL,
    `Q20` INTEGER NOT NULL,
    `Q21` INTEGER NOT NULL,
    `Q22` INTEGER NOT NULL,
    `Q23` INTEGER NOT NULL,
    `Q24` INTEGER NOT NULL,
    `Q25` INTEGER NOT NULL,
    `Q26` INTEGER NOT NULL,
    `Q27` INTEGER NOT NULL,
    `Q28` INTEGER NOT NULL,
    `CO1` INTEGER NOT NULL,
    `CO2` INTEGER NOT NULL,
    `CO3` INTEGER NOT NULL,
    `CO4` INTEGER NOT NULL,
    `CO5` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ESE` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `studentId` INTEGER NOT NULL,
    `Q1` INTEGER NOT NULL,
    `Q2` INTEGER NOT NULL,
    `Q3` INTEGER NOT NULL,
    `Q4` INTEGER NOT NULL,
    `Q5` INTEGER NOT NULL,
    `Q6` INTEGER NOT NULL,
    `Q7` INTEGER NOT NULL,
    `Q8` INTEGER NOT NULL,
    `Q9` INTEGER NOT NULL,
    `Q10` INTEGER NOT NULL,
    `Q11` INTEGER NOT NULL,
    `Q12` INTEGER NOT NULL,
    `Q13` INTEGER NOT NULL,
    `Q14` INTEGER NOT NULL,
    `Q15` INTEGER NOT NULL,
    `Q16` INTEGER NOT NULL,
    `Q17` INTEGER NOT NULL,
    `Q18` INTEGER NOT NULL,
    `Q19` INTEGER NOT NULL,
    `Q20` INTEGER NOT NULL,
    `Q21` INTEGER NOT NULL,
    `Q22` INTEGER NOT NULL,
    `Q23` INTEGER NOT NULL,
    `Q24` INTEGER NOT NULL,
    `Q25` INTEGER NOT NULL,
    `Q26` INTEGER NOT NULL,
    `Q27` INTEGER NOT NULL,
    `Q28` INTEGER NOT NULL,
    `CO1` INTEGER NOT NULL,
    `CO2` INTEGER NOT NULL,
    `CO3` INTEGER NOT NULL,
    `CO4` INTEGER NOT NULL,
    `CO5` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TotalCIA` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `studentId` INTEGER NOT NULL,
    `CO1` INTEGER NOT NULL,
    `CO2` INTEGER NOT NULL,
    `CO3` INTEGER NOT NULL,
    `CO4` INTEGER NOT NULL,
    `CO5` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Assignment` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `studentId` INTEGER NOT NULL,
    `Q1` INTEGER NOT NULL,
    `Q2` INTEGER NOT NULL,
    `CO1` INTEGER NOT NULL,
    `CO2` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Subject` ADD CONSTRAINT `Subject_departmentId_fkey` FOREIGN KEY (`departmentId`) REFERENCES `Department`(`depCode`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `pos` ADD CONSTRAINT `pos_subjectId_fkey` FOREIGN KEY (`subjectId`) REFERENCES `Subject`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Student` ADD CONSTRAINT `Student_subjectId_fkey` FOREIGN KEY (`subjectId`) REFERENCES `Subject`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CIA1` ADD CONSTRAINT `CIA1_studentId_fkey` FOREIGN KEY (`studentId`) REFERENCES `Student`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CIA2` ADD CONSTRAINT `CIA2_studentId_fkey` FOREIGN KEY (`studentId`) REFERENCES `Student`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ESE` ADD CONSTRAINT `ESE_studentId_fkey` FOREIGN KEY (`studentId`) REFERENCES `Student`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TotalCIA` ADD CONSTRAINT `TotalCIA_studentId_fkey` FOREIGN KEY (`studentId`) REFERENCES `Student`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Assignment` ADD CONSTRAINT `Assignment_studentId_fkey` FOREIGN KEY (`studentId`) REFERENCES `Student`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
